/**
 * PHAY SHOT IT - photographic catalog.
 * Single source of truth: every frame, its data, its collection memberships.
 * Filenames map to /public/images/phay-{NN}-{w}w.webp
 */

export type Frame = {
  id: string;
  /** base filename under /public/images (without -{w}w.webp suffix) */
  src: string;
  /** available rendered widths, ascending */
  widths: number[];
  /** intrinsic (largest) dimensions */
  w: number;
  h: number;
  title: string;
  location: string;
  coords: string;
  date: string;
  camera: string;
  lens: string;
  aperture: string;
  shutter: string;
  iso: string;
  film: string;
  alt: string;
  tone: "dark" | "light";
};

const F = (f: Frame) => f;

export const PHOTOS = {
  p01: F({
    id: "p01",
    src: "phay-01",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "08.08.2026",
    location: "ILORIN, NIGERIA",
    coords: "8°30′N 4°33′E",
    date: "08.08.2026",
    camera: "DIGITAL",
    lens: "PORTRAIT",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Young man in traditional brown Yoruba agbada with carved staff, outdoor portrait in Ilorin.",
    tone: "light",
  }),
  p02: F({
    id: "p02",
    src: "phay-02",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "14.06.2026",
    location: "ILORIN, NIGERIA",
    coords: "8°30′N 4°33′E",
    date: "14.06.2026",
    camera: "DIGITAL",
    lens: "PORTRAIT",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Woman in gold gele headwrap and brown feathered attire with gold beaded fan, outdoor portrait.",
    tone: "light",
  }),
  p03: F({
    id: "p03",
    src: "phay-03",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "22.05.2026",
    location: "ILORIN, NIGERIA",
    coords: "8°30′N 4°33′E",
    date: "22.05.2026",
    camera: "DIGITAL",
    lens: "PORTRAIT",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Smiling woman in embroidered brown lace dress with gold gele headwrap, standing outdoors.",
    tone: "light",
  }),
  p04: F({
    id: "p04",
    src: "phay-04",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "10.04.2026",
    location: "LAGOS, NIGERIA",
    coords: "6°27′N 3°24′E",
    date: "10.04.2026",
    camera: "DIGITAL",
    lens: "PORTRAIT",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Smiling woman in navy Dallas Cowboys jersey with pearl necklaces against green fence.",
    tone: "light",
  }),
  p05: F({
    id: "p05",
    src: "phay-05",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "18.03.2026",
    location: "LAGOS, NIGERIA",
    coords: "6°27′N 3°24′E",
    date: "18.03.2026",
    camera: "DIGITAL",
    lens: "PORTRAIT",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Man in white Arsenal jersey standing with arms crossed on turf pitch, wearing cap and watch.",
    tone: "light",
  }),
  p06: F({
    id: "p06",
    src: "phay-06",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "02.03.2026",
    location: "LAGOS, NIGERIA",
    coords: "6°27′N 3°24′E",
    date: "02.03.2026",
    camera: "DIGITAL",
    lens: "FULL-LENGTH",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Man in white Arsenal jersey standing full-length on astroturf with orange-soled shoes.",
    tone: "light",
  }),
  p07: F({
    id: "p07",
    src: "phay-07",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "15.02.2026",
    location: "LAGOS, NIGERIA",
    coords: "6°27′N 3°24′E",
    date: "15.02.2026",
    camera: "DIGITAL",
    lens: "PORTRAIT",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Woman in Dallas Cowboys jersey seated on grass with jeans and white sneakers, smiling.",
    tone: "light",
  }),
  p08: F({
    id: "p08",
    src: "phay-08",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "28.01.2026",
    location: "LAGOS, NIGERIA",
    coords: "6°27′N 3°24′E",
    date: "28.01.2026",
    camera: "DIGITAL",
    lens: "CLOSE-UP",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Young woman with braided updo holding a football, close-up portrait with intense gaze.",
    tone: "light",
  }),
  p09: F({
    id: "p09",
    src: "phay-09",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "12.01.2026",
    location: "LAGOS, NIGERIA",
    coords: "6°27′N 3°24′E",
    date: "12.01.2026",
    camera: "DIGITAL",
    lens: "PORTRAIT",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Two men greeting each other on a football pitch, one in England jersey, captured mid-handshake.",
    tone: "light",
  }),
  p10: F({
    id: "p10",
    src: "phay-10",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "20.12.2025",
    location: "ILORIN, NIGERIA",
    coords: "8°30′N 4°33′E",
    date: "20.12.2025",
    camera: "DIGITAL",
    lens: "FULL-LENGTH",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Man in oversized check shirt and white trousers walking on a long road, black and white portrait.",
    tone: "dark",
  }),
  p11: F({
    id: "p11",
    src: "phay-11",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "05.12.2025",
    location: "ILORIN, NIGERIA",
    coords: "8°30′N 4°33′E",
    date: "05.12.2025",
    camera: "DIGITAL",
    lens: "PORTRAIT",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Woman standing and man seated on ground in casual denim outfits, couple outdoor portrait.",
    tone: "light",
  }),
  p12: F({
    id: "p12",
    src: "phay-12",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "18.11.2025",
    location: "ILORIN, NIGERIA",
    coords: "8°30′N 4°33′E",
    date: "18.11.2025",
    camera: "DIGITAL",
    lens: "FULL-LENGTH",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Man in burgundy suit and white shirt with black tie, standing on brick pathway looking away.",
    tone: "light",
  }),
  p13: F({
    id: "p13",
    src: "phay-13",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "02.11.2025",
    location: "ILORIN, NIGERIA",
    coords: "8°30′N 4°33′E",
    date: "02.11.2025",
    camera: "DIGITAL",
    lens: "PORTRAIT",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Man in dark blazer and white t-shirt with cross necklace, looking down, outdoor portrait.",
    tone: "light",
  }),
  p14: F({
    id: "p14",
    src: "phay-14",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "15.10.2025",
    location: "ILORIN, NIGERIA",
    coords: "8°30′N 4°33′E",
    date: "15.10.2025",
    camera: "DIGITAL",
    lens: "PORTRAIT",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Group of five men in coordinated smart-casual outfits standing on brick plaza, fashion portrait.",
    tone: "light",
  }),
  p15: F({
    id: "p15",
    src: "phay-15",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "28.09.2025",
    location: "ILORIN, NIGERIA",
    coords: "8°30′N 4°33′E",
    date: "28.09.2025",
    camera: "DIGITAL",
    lens: "FULL-LENGTH",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Five young men in stylish smart outfits standing on brick plaza, group fashion portrait.",
    tone: "light",
  }),
  p16: F({
    id: "p16",
    src: "phay-16",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "10.09.2025",
    location: "ILORIN, NIGERIA",
    coords: "8°30′N 4°33′E",
    date: "10.09.2025",
    camera: "DIGITAL",
    lens: "PORTRAIT",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Woman crouching on road in all-black outfit with leather beret and sunglasses, street style.",
    tone: "light",
  }),
  p17: F({
    id: "p17",
    src: "phay-17",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "22.08.2025",
    location: "ILORIN, NIGERIA",
    coords: "8°30′N 4°33′E",
    date: "22.08.2025",
    camera: "DIGITAL",
    lens: "PORTRAIT",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Two men in traditional agbada attire with canes, outdoor cultural portrait.",
    tone: "light",
  }),
  p18: F({
    id: "p18",
    src: "phay-18",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "05.08.2025",
    location: "LAGOS, NIGERIA",
    coords: "6°27′N 3°24′E",
    date: "05.08.2025",
    camera: "DIGITAL",
    lens: "CLOSE-UP",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Woman with bandana and sunglasses in dark interior, moody close-up portrait.",
    tone: "dark",
  }),
  p19: F({
    id: "p19",
    src: "phay-19",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "18.07.2025",
    location: "ILORIN, NIGERIA",
    coords: "8°30′N 4°33′E",
    date: "18.07.2025",
    camera: "DIGITAL",
    lens: "PORTRAIT",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Woman in patterned blouse and green skirt with headscarf, outdoor portrait.",
    tone: "light",
  }),
  p20: F({
    id: "p20",
    src: "phay-20",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "02.07.2025",
    location: "ILORIN, NIGERIA",
    coords: "8°30′N 4°33′E",
    date: "02.07.2025",
    camera: "DIGITAL",
    lens: "PORTRAIT",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Woman in bandana and dark sunglasses, low-angle night portrait with dramatic lighting.",
    tone: "dark",
  }),
  p21: F({
    id: "p21",
    src: "phay-21",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "15.06.2025",
    location: "ILORIN, NIGERIA",
    coords: "8°30′N 4°33′E",
    date: "15.06.2025",
    camera: "DIGITAL",
    lens: "PORTRAIT",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Man in black suit with white t-shirt and sunglasses on brick pavement, fashion portrait.",
    tone: "light",
  }),
  p22: F({
    id: "p22",
    src: "phay-22",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "28.05.2025",
    location: "ILORIN, NIGERIA",
    coords: "8°30′N 4°33′E",
    date: "28.05.2025",
    camera: "DIGITAL",
    lens: "PORTRAIT",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Smiling man in brown check blazer with blue shirt and tie, close-up portrait.",
    tone: "light",
  }),
  p23: F({
    id: "p23",
    src: "phay-23",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "10.05.2025",
    location: "ILORIN, NIGERIA",
    coords: "8°30′N 4°33′E",
    date: "10.05.2025",
    camera: "DIGITAL",
    lens: "PORTRAIT",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Man in olive jacket and cap posed against coloured wall, lifestyle portrait.",
    tone: "light",
  }),
  p24: F({
    id: "p24",
    src: "phay-24",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "22.04.2025",
    location: "ILORIN, NIGERIA",
    coords: "8°30′N 4°33′E",
    date: "22.04.2025",
    camera: "DIGITAL",
    lens: "PORTRAIT",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Two women in brown and beige outfits, duo outdoor portrait.",
    tone: "light",
  }),
  p25: F({
    id: "p25",
    src: "phay-25",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "04.04.2025",
    location: "ILORIN, NIGERIA",
    coords: "8°30′N 4°33′E",
    date: "04.04.2025",
    camera: "DIGITAL",
    lens: "PORTRAIT",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Man in black suit jacket and white t-shirt looking down, fashion portrait in architectural setting.",
    tone: "light",
  }),
  p26: F({
    id: "p26",
    src: "phay-26",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "16.03.2025",
    location: "ILORIN, NIGERIA",
    coords: "8°30′N 4°33′E",
    date: "16.03.2025",
    camera: "DIGITAL",
    lens: "PORTRAIT",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Three women in traditional Nigerian wrappers, triple portrait outdoor.",
    tone: "light",
  }),
  p27: F({
    id: "p27",
    src: "phay-27",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "28.02.2025",
    location: "ILORIN, NIGERIA",
    coords: "8°30′N 4°33′E",
    date: "28.02.2025",
    camera: "DIGITAL",
    lens: "PORTRAIT",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Couple portrait with the man in a cap and woman in brown dress, outdoor.",
    tone: "light",
  }),
  p28: F({
    id: "p28",
    src: "phay-28",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "10.02.2025",
    location: "LAGOS, NIGERIA",
    coords: "6°27′N 3°24′E",
    date: "10.02.2025",
    camera: "DIGITAL",
    lens: "PORTRAIT",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Man seated on grass in casual outfit, relaxed lifestyle portrait.",
    tone: "light",
  }),
  p29: F({
    id: "p29",
    src: "phay-29",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "22.01.2025",
    location: "ILORIN, NIGERIA",
    coords: "8°30′N 4°33′E",
    date: "22.01.2025",
    camera: "DIGITAL",
    lens: "PORTRAIT",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Woman standing in white crop top and blue jeans on paved road, shot through foreground blur.",
    tone: "light",
  }),
  p30: F({
    id: "p30",
    src: "phay-30",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "05.01.2025",
    location: "ILORIN, NIGERIA",
    coords: "8°30′N 4°33′E",
    date: "05.01.2025",
    camera: "DIGITAL",
    lens: "PORTRAIT",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Man in dark suit on cobblestone pavement, full-length fashion portrait.",
    tone: "light",
  }),
  p31: F({
    id: "p31",
    src: "phay-31",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "18.12.2025",
    location: "LAGOS, NIGERIA",
    coords: "6°27′N 3°24′E",
    date: "18.12.2025",
    camera: "DIGITAL",
    lens: "PORTRAIT",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Woman in bold graphic tee and visor sunglasses, low-angle night portrait.",
    tone: "dark",
  }),
  artist: F({
    id: "artist",
    src: "phay-artist",
    widths: [700, 960],
    w: 960,
    h: 1280,
    title: "THE PHOTOGRAPHER",
    location: "ILORIN, NIGERIA",
    coords: "8°30′N 4°33′E",
    date: "08.08.2026",
    camera: "SELFIE",
    lens: "",
    aperture: "",
    shutter: "",
    iso: "",
    film: "",
    alt: "Phay, the photographer behind Phay Shot It, in a green jacket with lanyard.",
    tone: "light",
  }),
} satisfies Record<string, Frame>;

export type PhotoId = keyof typeof PHOTOS;
export type Photo = (typeof PHOTOS)[PhotoId];

export const srcSetFor = (p: Photo) =>
  p.widths.map((w) => `/images/${p.src}-${w}w.webp ${w}w`).join(", ");
export const largestSrc = (p: Photo) => `/images/${p.src}-${p.widths[p.widths.length - 1]}w.webp`;

/* --- collections --- */

export type Collection = {
  id: string;
  index: string;
  name: string;
  line: string;
  years: string;
  photos: Photo[];
};

const pick = (...ids: PhotoId[]) => ids.map((id) => PHOTOS[id]);

export const COLLECTIONS: Collection[] = [
  {
    id: "portraits",
    index: "01",
    name: "PORTRAITS",
    line: "People, before they perform.",
    years: "2025 - 2026",
    photos: pick("p01", "p03", "p08", "p12", "p22", "p25"),
  },
  {
    id: "lifestyle",
    index: "02",
    name: "LIFESTYLE",
    line: "Drip captured, every time.",
    years: "2025 - 2026",
    photos: pick("p04", "p05", "p06", "p07", "p10", "p16"),
  },
  {
    id: "culture",
    index: "03",
    name: "CULTURE",
    line: "Heritage, styled and worn.",
    years: "2025 - 2026",
    photos: pick("p02", "p17", "p19", "p26"),
  },
  {
    id: "groups",
    index: "04",
    name: "GROUPS",
    line: "Together, the frame gets richer.",
    years: "2025 - 2026",
    photos: pick("p09", "p11", "p14", "p15", "p24", "p27"),
  },
  {
    id: "vault",
    index: "05",
    name: "THE VAULT",
    line: "Every frame, unfiltered.",
    years: "2025 - 2026",
    photos: pick(
      "p01", "p02", "p03", "p04", "p05", "p06", "p07", "p08", "p09", "p10",
      "p11", "p12", "p13", "p14", "p15", "p16", "p17", "p18", "p19", "p20",
      "p21", "p22", "p23", "p24", "p25", "p26", "p27", "p28", "p29", "p30",
      "p31"
    ),
  },
];

/* --- the story (pinned scrollytelling sequence) --- */

export type StoryFrame = {
  photo: Photo;
  step: string;
  time: string;
  line: string;
};

export const STORY = {
  title: "LAGOS & ILORIN",
  kicker: "A STORY IN FOUR FRAMES",
  date: "2025 - 2026",
  frames: <StoryFrame[]>[
    {
      photo: PHOTOS.p01,
      step: "CULTURE",
      time: "01",
      line: "Tradition meets the lens.",
    },
    {
      photo: PHOTOS.p18,
      step: "MOOD",
      time: "02",
      line: "Every shadow tells a story.",
    },
    {
      photo: PHOTOS.p14,
      step: "SQUAD",
      time: "03",
      line: "Five deep, styled to the nines.",
    },
    {
      photo: PHOTOS.p08,
      step: "FOCUS",
      time: "04",
      line: "The portrait that stares back.",
    },
  ],
};

/* --- field map --- */

export type MapNode = {
  id: string;
  city: string;
  coords: string;
  years: string;
  /** position, % of map plane (equirectangular-ish) */
  x: number;
  y: number;
  photo: Photo;
  photos: Photo[];
};

export const MAP_NODES: MapNode[] = [
  {
    id: "lagos",
    city: "LAGOS",
    coords: "6°27′N 3°24′E",
    years: "2025 - 2026",
    x: 38,
    y: 55,
    photo: PHOTOS.p04,
    photos: pick("p04", "p05", "p06", "p07", "p09", "p18", "p28", "p31"),
  },
  {
    id: "ilorin",
    city: "ILORIN",
    coords: "8°30′N 4°33′E",
    years: "2025 - 2026",
    x: 62,
    y: 35,
    photo: PHOTOS.p01,
    photos: pick("p01", "p02", "p03", "p10", "p11", "p12", "p13", "p14", "p15", "p16", "p17", "p19", "p20", "p21", "p22", "p23", "p24", "p25", "p26", "p27", "p29", "p30"),
  },
];

/* --- pricing --- */

export type PricingPackage = {
  index: string;
  name: string;
  tagline: string;
  features: string[];
  price: string;
  highlight?: boolean;
};

export const PRICING: PricingPackage[] = [
  {
    index: "01",
    name: "ESSENTIALS",
    tagline: "For a quick, polished solo portrait or single convocation moment",
    features: [
      "4 professionally edited photos",
      "5 selected unedited photos",
      "Professional camera & lighting setup",
      "1 outfit",
      "1 location",
      "Same-day preview",
    ],
    price: "₦50,000",
  },
  {
    index: "02",
    name: "SIGNATURE",
    tagline: "Ideal for a full convocation day or a considered lifestyle session",
    features: [
      "8 professionally edited photos",
      "10 selected unedited photos",
      "Professional camera & lighting setup",
      "2 outfits",
      "Flexible locations",
      "Pre-shoot styling consultation",
      "48-hour delivery",
    ],
    price: "₦70,000",
    highlight: true,
  },
  {
    index: "03",
    name: "LEGACY",
    tagline: "For families and milestone celebrations that deserve the full story",
    features: [
      "12 professionally edited photos, cinematic color grade",
      "10 selected unedited photos",
      "Professional camera & lighting setup",
      "3 outfits",
      "Multiple locations",
      "Behind-the-scenes highlight reel",
      "Printed photo set included",
      "Priority editing & delivery",
    ],
    price: "₦100,000",
  },
];
